### ISSUE TITLE
add StringCalculator kata

### ISSUE THREAD

**Issue by jukecraft** [softwarecrafters/kata-log#10]
http://osherove.com/tdd-kata-1/

**Comment by rachelcarmena** [comment]
Hi @franziskas ! I've included it in [this PR](https://github.com/Egga/kata-log/pull/21)

**Comment by rachelcarmena** [comment]
Hi @franziskas ! I've included it in [this PR](https://github.com/Egga/kata-log/pull/21) :tada:

**Comment by Egga-zz** [comment]
@franziskas @rachelcarmena do you want to close this issue yourself?

**Comment by rachelcarmena** [comment]
Thanks @Egga and @franziskas !
