### ISSUE TITLE
Add Gabriele's Tell-Don't-Ask kata

### ISSUE THREAD

**Issue by jukecraft** [softwarecrafters/kata-log#11]
https://github.com/gabrieletondi/tell-dont-ask-kata

**Comment by rachelcarmena** [comment]
Hi @franziskas ! I've included it in [this PR](https://github.com/Egga/kata-log/pull/21) :tada:

**Comment by Egga-zz** [comment]
@franziskas @rachelcarmena do you want to close this issue yourself?

**Comment by rachelcarmena** [comment]
Thanks @Egga and @franziskas !
