### ISSUE TITLE
Kata-log Christmas Lights missing info

### ISSUE THREAD

**Issue by relentless** [softwarecrafters/kata-log#17]
Hi Egga, your kata log is great – I run dojos at work and also Leeds Code Dojo so resources like this are really useful.

One thing I noticed with the Christmas Lights Kata is that it refers to ‘Santa’s instructions’, but these are never given (or at least, I couldn't see them).  In the Advent of Code where it’s from, you need to log in to get the instructions which are like:

turn on 887,9 through 959,629
turn on 454,398 through 844,448
turn off 539,243 through 559,965
turn off 370,819 through 676,868
turn off 145,40 through 370,997
turn off 301,3 through 808,453
turn on 351,678 through 951,908
toggle 720,196 through 897,994
toggle 831,394 through 904,860
…

You then need to submit your answer for validation.

I think this could do with a couple of changes to be more of a typical kata, focusing more on the parsing bit than finding a specific answer.  Could be an interesting one though.

**Comment by Egga-zz** [comment]
@relentless what do you think about the draft?

**Comment by eggstrema** [comment]
Added the instructions. I found this to be a fun exercise to do as a christmas special in a group that had weekly kata sessions. You're absolutely welcome to submit a PR to make this more like a typical kata.
