### ISSUE TITLE
 Minimalist Coder Constraint not clear.

### ISSUE THREAD

**Issue by elafontaine** [softwarecrafters/kata-log#26]
I was not able to understand the minimalist coder constraint.  Maybe a small explanation would help me understand :)

**Comment by eggstrema** [comment]
Oh, yeah, you're right. It's an empty page. Ilke proposed that name as an alternative for the "lazy coder" constraint. We should add a description.

**Comment by elafontaine** [comment]
Thank uou 👍 :)
