### ISSUE TITLE
Constraint.No Primitives -> String is not a primitive value

### ISSUE THREAD

**Issue by dounuthase** [softwarecrafters/kata-log#35]
Hi all,
I saw today this cool contraint but was wondering what primitiv values means. After researching, I read that "Boolean , Byte , SByte , Int16 , UInt16 , Int32 , UInt32 , Int64 , UInt64 , IntPtr , UIntPtr , Char , Double und Single" are primitiv but string is not.

Can you fix the description, if I am correct. Thanks :)

**Comment by eggstrema** [comment]
I rephrased that a little. There is a whole paragraph about Strings explaining what is meant.
