### ISSUE TITLE
Please clarify rules for Parallel Change Kata

### ISSUE THREAD

**Issue by HelgeStenstrom** [softwarecrafters/kata-log#36]
The way I've learnt about TDD is to write the tests first, run them and watch them fail. Then write the code that make the tests pass.

The rule, as stated on https://kata-log.rocks/parallel-change-kata is "The tests must not be red at any time. No compile-errors, no failures." The way I read it, is that the normal TDD flow can't be used. It looks more like the TCR (test && commit || revert) flow, where any test failure leads to the code being reverted to the last green state. See https://medium.com/@kentbeck_7670/test-commit-revert-870bbd756864.

The rule can be more explicit about this. I'm not sure I'm reading the rule the way the author intended.

**Comment by rradczewski** [comment]
Hi @HelgeStenstrom, this Kata is a refactoring Kata to practice changing code without ever breaking the existing tests (or clients for that matter).

See [Martin Fowler on the ParallelChange pattern](https://martinfowler.com/bliki/ParallelChange.html).

A new test covering the "expand" step can/should fail, but the focus here is that at any point of when you type a syntactically valid statement, the existing tests (and client implementation) must not fail.

Hope that clarifies things. If that helps you and you decide to do the kata, maybe consider submitting a PR with some more details to help the next one 🙂

**Comment by HelgeStenstrom** [comment]
I already did the kata before I submitted this question. I didn't really follow the suggestions from Danilo Sato in the article you linked; he changes the API, and I see no need for that here. (In his article, he also changes the internal representation from an array to a map of coordinates; in my opinion, the API change and the internal representation change do not need to be related to each other. I would do them separately).

I really feel that the TCR methodology is relevant in this kata. It forces you to have code that is green all the time. Therefore, it's worth mentioning.

**Comment by eggstrema** [comment]
Hi Helge!

We have a constraint (called Baby Steps) that describes what you refer to as TCR. If you do this kata cleanly there is not gonna be a red phase and no need to revert any changes.

To repeat Raimos point: this is a refactoring kata with existing tests. Your task is to change the code without breaking the tests. This kata focuses less on TDD and more on "not breaking existing code". I removed the TDD tag from. Can we close this issue now?

**Comment by HelgeStenstrom** [comment]
Hi @eggstrema , thanks for the answer. You can close the issue.
